### ISSUE TITLE
Start yambar when starting labwc

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2648]
Needs to be added to woof-code/rootfs-petbuilds/labwc/root/.config/labwc/autostart, with sane configuration files.

**Comment by 01micko** [comment]
I want to make a basic config.yml without the fancy icon font. I'll get on it soon.

**Comment by 01micko** [comment]
Actually, the `pupmoon` font is now at ibiblio : https://distro.ibiblio.org/puppylinux/sources/p/pupmoon_font-1.0.tar.xz
`bc0bb515ec85b726dd3c22545745f30a225316da8685519d5f8ba14f4558d07d  pupmoon_font-1.0.tar.xz` (sha256)

It's dual licenced; GPL and CC BY 4.0 - see https://icomoon.io/app/#/select/library (IcoMoon - Free)

**Comment by 01micko** [comment]
Just tested `pupmoon` now

```
~$ killall yambar
~$ yambar
info: fcft.c:269: fcft: 1.7.0-35-gd7a58e4 (Oct 18 2021, branch 'master') +graphemes +runs
info: fcft.c:279: fontconfig: 2.13.92
info: fcft.c:285: freetype: 2.11.0
info: fcft.c:760: /usr/share/fonts/TTF/DejaVuSans.ttf: size=12.00pt/13px, dpi=75.00
info: fcft.c:760: /usr/share/fonts/TTF/DejaVuSans.ttf: size=13.44pt/14px, dpi=75.00
info: fcft.c:760: /usr/share/fonts/TTF/DejaVuSans.ttf: size=19.20pt/20px, dpi=75.00
info: bar/wayland.c:527: monitor: DVI-D-1: 1920x1080+0+0 (480x270mm)
info: bar/wayland.c:527: monitor: VGA-1: 1920x1080+1920+0 (480x270mm)
info: modules/network.c:409: wlan0: ifindex=3
info: fcft.c:760: /usr/share/fonts/TTF/pupmoon.ttf: size=19.20pt/20px, dpi=75.00
info: fcft.c:760: /usr/share/fonts/TTF/pupmoon.ttf: size=13.44pt/14px, dpi=75.00
info: modules/alsa.c:325: hw:Generic,Master: channels: Front Left (🔊)
info: modules/alsa.c:363: hw:Generic,Master: volume range=0-64, current=51 (sources: volume=Front Left, muted=Front Left)
```

Here is the config, should be fairly generic.


```yml
# Typical setup

# fonts we'll be re-using here and there
pupmoon: &ico:pixelsize=20
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 28
  location: top
  monitor: "DVI-D-1"
  spacing: 5
  margin: 7

  # Default font
  font: DejaVuSans:pixelsize=14

  foreground: dddddddd
  background: 11111133

  border:
    width: 1
    color: 555555cc
    margin: 5
    top-margin: 0

  left:
    - label:
        content:
          - string: { on-click: pupmenu, text:  , left-margin: 12, right-margin: 18, font: *ico, foreground: ffe624ff,  deco: {background: {color: 11111133}} }
    - label:
        content:
          string:
            on-click: defaultterminal
            text: 
            left-margin: 5
            right-margin: 5
            font: *ico
            foreground: dddddddd
            deco: {background: {color: 00000033}}
    - label:
        content:
          string:
            on-click: firefox
            text: 
            left-margin: 5
            right-margin: 5
            font: *ico
            foreground: dd00dddd
            deco: {background: {color: 00000033}}
    - label:
        content:
          string:
            on-click: pcmanfm
            text: 
            left-margin: 5
            right-margin: 5
            font: *ico
            foreground: ffe198dd
            deco: {background: {color: 00000033}}
    - label:
        content:
          string:
            on-click: pmount
            text: 
            left-margin: 5
            right-margin: 5
            font: *ico
            foreground: 3c3c3cdd
            deco: {background: {color: 00000033}}
    - label:
        content:
          string:
            on-click: geany
            text: 
            left-margin: 7
            right-margin: 7
            font: *ico
            foreground: dddddddd
            deco: {background: {color: 00000033}}

    - foreign-toplevel:
        content:
          map:
            tag: activated
            values:
              false: {empty: {}}
              true:
                - string: {text: "{title}"}

  right:
    - removables:
        anchors:
          drive: &drive { text: , font: *ico, foreground: 3d3d3ddd}
          optical: &optical {text: , font: *ico, foreground: bdbdbddd}
        spacing: 5
        content:
          map:
            tag: mounted
            values:
              false:
                map:
                  tag: optical
                  on-click: udisksctl mount -b {device}
                  values:
                    false: [{string: *drive}, {string: {text: "{label}"}}]
                    true: [{string: *optical}, {string: {text: "{label}"}}]
              true:
                map:
                  tag: optical
                  on-click: udisksctl unmount -b {device}
                  values:
                    false:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    true:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
    - network:
        name: wlan0
        content:
          map:
            tag: state
            default: {string: {text: , font: *ico, foreground: 00ff0066, right-margin: 4}}
            values:
              down: {string: {text: , font: *ico, foreground: ff0000ff}}
              up:
                map:
                  tag: ipv4
                  default:
                    - string: {text: , font: *ico, foreground: 00ff0066, right-margin: 4}
                    - string: {text: "{ssid}"}
                  values:
                    "":
                      - string: {text: , font: *ico, foreground: 00ff0066, right-margin: 4}
                      - string: {text: "{ssid}", foreground: ffffff66}
    - alsa:
        card: hw:Generic
        mixer: Master
        content:
          map:
            tag: online
            values:
              false: {string: {text: , font: *ico, foreground: ff0000ff}}
              true:
                map:
                  on-click: foot -W 80x6 -e pulsemixer
                  tag: muted
                  values:
                    true: {string: {text: , font: *ico, foreground: ffffff66}}
                    false:
                      ramp:
                        tag: volume
                        items:
                          - string: {text: , font: *ico, on-click: foot -W 80x6 -e pulsemixer}
                          - string: {text: , font: *ico, on-click: foot -W 80x6 -e pulsemixer}
                          - string: {text: , font: *ico, on-click: foot -W 80x6 -e pulsemixer}
                          - string: {text: , font: *ico, on-click: foot -W 80x6 -e pulsemixer}
                          - string: {text: , font: *ico, on-click: foot -W 80x6 -e pulsemixer}
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *ico, on-click: yad --calendar, foreground: bbcfffdd}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: logout_gui
            text: 
            font: *ico
            foreground: dd0033dd
```


Screeny

![yam](https://user-images.githubusercontent.com/1019119/143764278-41b56c33-eed4-4332-b43e-47acf26b2a5d.png)
